### ISSUE TITLE
Comments toevoegen aan functies

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/real-time-web-2021#12]
https://github.com/ralfz123/real-time-web-2021/blob/39046577306166efe788cc85ce75247abbff8691/modules/fetch.js#L16

Ik weet niet zo goed wat `queryChecker` doet. Het checkt een query? Waarom? Handig om erboven even neer te zetten wat het doet (omschrijving), wat de parameter `query` is (parameters) en wat het returnt (return). Als het goed is, doet VS Code dit al automatisch als je `/**` typt boven een functie.

Een functie als `async function getRecipeDatas(id)` is voor mij best logisch: het haalt de data van een recept. Tóch is het ook handig om het bij dit soort functies neer te zetten. De omschrijving kan dan wel wat korter, maar wat returnt deze functie? Wat voor type is `filteredData`. Object? Array?

Als je dit consistent doet bij elke functie, begrijpt de lezer (en de toekomstige developer) waarom deze functies er zijn en wat ze doen. Stel dat er een hoop functies zijn, dan wil je ze niet allemaal doorlezen om te kijken wat ze doen. Als je de omschrijving leest, weet je al genoeg.

**Comment by jochemvogel** [comment]
Edit: ik zie overigens dat je het hier wel doet: https://github.com/ralfz123/real-time-web-2021/blob/39046577306166efe788cc85ce75247abbff8691/modules/filter.js#L1

Doe het dan ook gelijk bij de rest 😉

**Comment by jochemvogel** [comment]
En doe het consistent want hier gebruik je weer `//` i.p.v. `/**`:

https://github.com/ralfz123/real-time-web-2021/blob/39046577306166efe788cc85ce75247abbff8691/modules/filter.js#L52

**Comment by ralfz123** [comment]
Thanks man. Goed punt! me code is op dit moment een mess, omdat ik met sockets zit te klooien. Ik ga er zsm mee aan de slag :)
