### ISSUE TITLE
Requires ordenen

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/real-time-web-2021#13]
https://github.com/ralfz123/real-time-web-2021/blob/39046577306166efe788cc85ce75247abbff8691/server.js#L1

Zelf vind ik het wel fijn om deze te ordenen. Je doet dit al enigszins door de `require('dotenv').config()` eronder te zetten, maar de requires erboven zijn een combinatie van packages en modules.

Neem het niet zo maar over, maar ik zou iets doen als:

```javascript
require('dotenv').config();

const express = require('express');
const firebase = require('firebase');
const uuid = require('uuid').v4;
const bodyParser = require('body-parser');

const { getData, getRecipeDatas } = require('./modules/fetch.js');

const http = require('http').createServer(app);
const io = require('socket.io')(http);

const port = process.env.PORT || 5000;

const app = express();

```

Er is geen goed of fout, maar ik vind het nu gewoon iets te rommelig. Kijk maar even hoe jij het zou kunnen doen 🙂

'Ik' gebruik app voordat het geïnitialiseerd is: dus ook niet goed eigenlijk. Daarom: er is geen goed of fout.

**Comment by ralfz123** [comment]
Goede feedback! Hier ben ik zelf al een tijdje mee bezig om hoe je het het best kan doen. Ik vind dat dit altijd een rommeltje blijft (pcks en modules door elkaar), tenzij je het voorziet van comments. Maar dat is ook weer een beetje "te"...
