### ISSUE TITLE
Else vervangen met return

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/real-time-web-2021#14]
https://github.com/ralfz123/real-time-web-2021/blob/39046577306166efe788cc85ce75247abbff8691/public/js/main.js#L28

Je gebruikt nu regelmatig een `else { null; }` in je conditional statements, maar dit kan eigenlijk mooier (als je het mij vraagt)

Vind het zelf wel netter om het zo te doen:

```javascript
if (ingredientsForm) {
  ingredientsForm.addEventListener('submit', function (e) {
    e.preventDefault();
    if (inputQuery.value) {
      loader('show');
      socket.emit('query', { query: inputQuery.value });
      // inputQuery.value = '';
    }
  });

return;
}

```

Het doet hetzelfde en zegt als het ware: om het moment dat het zo is, voer het uit en `return`. Dit gaat dan verder als het ware.

Waarom die enter? Vind zelf altijd wel goed om boven een return altijd een enter te zetten, zodat het allemaal wat duidelijker is. Is puur persoonlijke voorkeur, dus zou je weg kunnen laten.

**Comment by jochemvogel** [comment]
Als je het leuk vindt, zou je eens naar het [Early Return Pattern](https://forum.freecodecamp.org/t/the-return-early-pattern-explained-with-javascript-examples/19364) kunnen kijken. Denk dat het je in de toekomst zeker gaat helpen. Is voornamelijk handig voor hele lange statements (waardoor je niet enorm geneste `if else` statements krijgt).

Is met name daar voor bedoeld, maar je kunt het ook gewoon voor kleinere dingen toepassen.

Hier nog ander artikel: https://codeburst.io/code-js-in-stlye-early-return-3462323e30d1

Google kun je genoeg vinden.

**Comment by ralfz123** [comment]
Thanks Jochem! Handige resources en mooi concept om verder op in te duiken, thanks! :fire:
