### ISSUE TITLE
Live link ook in je project zetten

### ISSUE THREAD

**Issue by NielsPeeters96** [ralfz123/real-time-web-2021#15]
Ziet er goed uit allemaal Ralf, je bent goed bezig!
Je kan alleen de live link nog rechts in je Github als website plaatsen zodat het een stuk duidelijker is dat je applicatie ook live staat.

**Comment by ralfz123** [comment]
Thanks! En trouwens, die link staat daar wel...
![Screenshot 2021-04-23 at 10 22 13](https://user-images.githubusercontent.com/55750121/115842097-c7eae900-a41d-11eb-8971-ab9617ef78ad.png)

**Comment by NielsPeeters96** [comment]
Zie het nu ook inderdaad, misschien een bug want kon hem net niet vinden namelijk. Volgende week vertrouwen in de beoordeling?

**Comment by ralfz123** [comment]
Haha okay!

Ja opzich wel, hoewel ik wel nog even moet gasgeven om de laatste dingen te fixen! 
Jij?

**Comment by NielsPeeters96** [comment]
Nice man! Gaat wel goedkomen bij jou denk ik zo.
Ja ik heb er ook wel vertrouwen in, maar ik moet ook nog de laatste loodjes leggen en verschillende keywords programmeren.

**Comment by ralfz123** [comment]
lekker man! Het einde is in zicht! Pak voor de zekerheid nog even de rubric erbij om de laatste puntjes te checken! 🔥
