### ISSUE TITLE
Example env

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/real-time-web-2021#2]
Goed dat er in de README staat welke API het is, maar hoe wordt deze aangeroepen? `API_KEY`? `APIKEY`? `API-KEY`? `KEY`? Je snapt wat ik bedoel. Even voorbeeld env (`env.example` bijv) maken.

**Comment by jochemvogel** [comment]
@ralfz123 Goed dat je het nu wel gedaan hebt: alleen hoe kan ik de data van Firebase halen? Wat is Firebase? Moet ik dan een account aanmaken ofzo? Gekkigheid, maar dit staat niet in de README. Handig om ook even te vermelden hoe ik aan de keys kom 🙂

**Comment by ralfz123** [comment]
Yes thanks Jochem! Echter heb ik dit heel klakkeloos in me readme gezet als reminder voor mezelf om later aan te vullen. Maar thanks man!
