### ISSUE TITLE
<head> in head.ejs zetten

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/real-time-web-2021#5]
https://github.com/ralfz123/real-time-web-2021/blob/afd871b22fb8fd8267be4cf55245f16e276e5183/views/index.ejs#L4

Dan hoef je alleen maar includes head te doen en hoef je niet nog een heel head element te maken. Is op de langere termijn wat handiger, want zou je kunnen vergeten. Zet de logica van de <head> gewoon in de head.

**Comment by ralfz123** [comment]
Of een dynamische title zoals @sjagoori dat doet 😄
